
image: registry.gitlab.com/wireshark/wireshark-containers/ubuntu-dev

variables:
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  CCACHE_MAXSIZE: "1"

cache:
  paths:
    - ccache

stages:
  - build
  - deploy

compile:
  stage: build
  before_script:
    - apt-get -qq update
    - apt-get -y install lua-ldoc
    - git clone --depth 1 https://gitlab.com/wireshark/wireshark.git
  script:
    # Build and install wireshark from the master branch
    - cd wireshark
    - mkdir build
    - cd build
    - cmake -G Ninja -DENABLE_WERROR=No -DENABLE_CCACHE=Yes ..
    - ninja
    - ninja install
    # Build the plugin
    - cd $CI_PROJECT_DIR
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
    - make docs
    - make package
  after_script:
    - ccache --show-stats
  artifacts:
    paths:
      - build/wireshark-lua-plugin-*.tar.gz
      - build/doc

pages:
  stage: deploy
  dependencies:
    - compile
  script:
    - mv build/doc public/
  artifacts:
    paths:
      - public
  only:
    - main
