


stages:
  - build
  - deploy

compile-gcc:
  image: registry.gitlab.com/jvalverde/wireshark-lua-plugin/wireshark-ubuntu-dev
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make install
    - make test
    - make docs
    - make package
  artifacts:
    paths:
      - build/wireshark-*-lua-plugin-*.tar.gz
      - build/doc

compile-mingw:
  image: registry.gitlab.com/jvalverde/wireshark-lua-plugin/wireshark-mingw-dev
  stage: build
  script:
    - mkdir build
    - cd build
    - Wireshark_DIR=/opt/wireshark/cmake mingw64-cmake ..
    - make
    - make package_zip
  artifacts:
    paths:
      - build/wireshark-*-lua-plugin-*.zip

pages:
  stage: deploy
  dependencies:
    - compile-gcc
  script:
    - mv build/doc public/
  artifacts:
    paths:
      - public
  only:
    - main
