
image: registry.gitlab.com/jvalverde/wireshark-lua-plugin/ubuntu

variables:
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  CCACHE_MAXSIZE: "1"

cache:
  paths:
    - ccache

stages:
  - build
  - deploy

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make install
    - make test
    - make docs
    - make package
  after_script:
    - ccache --show-stats
  artifacts:
    paths:
      - build/wireshark-*-lua-plugin-*.tar.gz
      - build/doc

pages:
  stage: deploy
  dependencies:
    - compile
  script:
    - mv build/doc public/
  artifacts:
    paths:
      - public
  only:
    - main
