
image: registry.gitlab.com/jvalverde/wireshark-lua-plugin/ubuntu

stages:
  - build
  - deploy

compile:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make install
    - make test
    - make docs
    - make package
  artifacts:
    paths:
      - build/wireshark-*-lua-plugin-*.tar.gz
      - build/doc

pages:
  stage: deploy
  dependencies:
    - compile
  script:
    - mv build/doc public/
  artifacts:
    paths:
      - public
  only:
    - main
